# Generated by Django 4.2.5 on 2023-09-09 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scraper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCode', models.CharField(default='', max_length=20)),
                ('price', models.IntegerField(default='', max_length=15)),
                ('neighborhood', models.CharField(default='', max_length=40)),
                ('commune', models.CharField(default='', max_length=40)),
                ('address', models.CharField(default='', max_length=40)),
            ],
        ),
    ]
