# Generated by Django 4.2.5 on 2023-09-09 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraper',
            name='price',
            field=models.IntegerField(default=''),
        ),
    ]
