# Generated by Django 4.2.5 on 2023-09-10 18:37

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_scraper_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraper',
            name='idCode',
            field=models.CharField(default=api.models.generateIdCode, max_length=20),
        ),
    ]
